version: '3.5'
services:
    postgres:
        image: postgres:11
        container_name: identity_postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        networks:
            - identity
        volumes:
            - postgres:/data/db

networks:
    identity:
        name: identity-network
        internal: true

volumes:
    postgres:
        driver: local
    redis:
        driver: local
