version: '3.5'
services:
    api:
        image: ranger.identity:dev
        container_name: identity
        ports:
            - '4000:5000'
        networks:
            - ranger

networks:
    ranger:
        name: ranger-network
        external: true
